"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ChevronDown, RefreshCw } from "lucide-react";

type Route={id:string;title:string;type:string;proposition:string;accent:string;bigIdea:string;why:string;mechanism:string;social:string;ugc:string;offline:string;pr:string;product:string;risk:string};
const details:[string,keyof Route][]=[["核心创意","bigIdea"],["为什么是现在","why"],["人群洞察","proposition"],["品牌角色","product"],["战役机制","mechanism"],["社交钩子","social"],["UGC机制","ugc"],["线下体验","offline"],["公关角度","pr"],["产品角色","product"],["潜在风险","risk"]];
const color:Record<string,string>={acid:"bg-acid",clay:"bg-clay text-white",sage:"bg-sage text-white",paper:"bg-white/70"};
const typeLabel:Record<string,string>={"Personalization IP":"个性化品牌IP","Sensory Campaign":"感官战役","Social Experience":"社交体验","Visual UGC":"视觉共创"};

export function RouteCard({route}:{route:Route}){const [open,setOpen]=useState(route.id==="01"); return <article className={`border border-black/20 ${color[route.accent]}`}><button onClick={()=>setOpen(!open)} className="flex w-full items-start justify-between p-6 text-left md:p-8"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] opacity-55">路线 {route.id} / {typeLabel[route.type]??route.type}</p><h2 className="mt-14 max-w-lg font-serif text-4xl leading-none tracking-[-.04em] md:text-5xl">{route.title}</h2><p className="mt-5 text-sm opacity-65">{route.proposition}</p></div><span className={`grid h-10 w-10 place-items-center rounded-full border border-current/30 transition ${open?"rotate-180":""}`}><ChevronDown size={17}/></span></button>{open&&<div className="border-t border-current/20 p-6 md:p-8"><div className="grid gap-x-8 md:grid-cols-2">{details.map(([label,key])=><div key={label} className="border-b border-current/20 py-4"><p className="text-[9px] font-semibold uppercase tracking-[.16em] opacity-45">{label}</p><p className="mt-2 text-sm leading-relaxed opacity-80">{route[key]}</p></div>)}</div>{route.id==="01"&&<Link href="/critic" className="mt-7 inline-flex items-center gap-2 border-b border-current pb-1 text-sm font-semibold">深化这条路线 <ArrowRight size={14}/></Link>}</div>}<button onClick={()=>setOpen(!open)} className="w-full border-t border-current/20 px-6 py-4 text-left text-[10px] uppercase tracking-[.14em] opacity-50"><RefreshCw size={11} className="mr-2 inline"/>点击{open?"收起":"展开"}完整方案</button></article>}
