"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ChevronDown, RefreshCw } from "lucide-react";

type Route={id:string;title:string;type:string;proposition:string;accent:string;bigIdea:string;why:string;mechanism:string;social:string;ugc:string;offline:string;pr:string;product:string;risk:string};
const details:[string,keyof Route][]=[["Big Idea","bigIdea"],["Why Now","why"],["Human Insight","proposition"],["Brand Role","product"],["Campaign Mechanism","mechanism"],["Social Hook","social"],["UGC Mechanism","ugc"],["Offline","offline"],["PR Angle","pr"],["Product Role","product"],["Risk","risk"]];
const color:Record<string,string>={acid:"bg-acid",clay:"bg-clay text-white",sage:"bg-sage text-white",paper:"bg-white/70"};

export function RouteCard({route}:{route:Route}){const [open,setOpen]=useState(route.id==="01"); return <article className={`border border-black/20 ${color[route.accent]}`}><button onClick={()=>setOpen(!open)} className="flex w-full items-start justify-between p-6 text-left md:p-8"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] opacity-55">Route {route.id} / {route.type}</p><h2 className="mt-14 max-w-lg font-serif text-4xl leading-none tracking-[-.04em] md:text-5xl">{route.title}</h2><p className="mt-5 text-sm opacity-65">{route.proposition}</p></div><span className={`grid h-10 w-10 place-items-center rounded-full border border-current/30 transition ${open?"rotate-180":""}`}><ChevronDown size={17}/></span></button>{open&&<div className="border-t border-current/20 p-6 md:p-8"><div className="grid gap-x-8 md:grid-cols-2">{details.map(([label,key])=><div key={label} className="border-b border-current/20 py-4"><p className="text-[9px] font-semibold uppercase tracking-[.16em] opacity-45">{label}</p><p className="mt-2 text-sm leading-relaxed opacity-80">{route[key]}</p></div>)}</div>{route.id==="01"&&<Link href="/critic" className="mt-7 inline-flex items-center gap-2 border-b border-current pb-1 text-sm font-semibold">Develop this route <ArrowRight size={14}/></Link>}</div>}<div className="border-t border-current/20 px-6 py-4 text-[10px] uppercase tracking-[.14em] opacity-50"><RefreshCw size={11} className="mr-2 inline"/>Click to {open?"collapse":"expand"}</div></article>}
