"use client";
import {useState,useEffect} from 'react';import {socialContent} from '@/data/socialContent';import {kvStyles} from '@/data/kvStyles';import {videoStoryboard} from '@/data/videoStoryboard';import {creatorBrief,creatorGuidelines} from '@/data/creatorBrief';import {generateCopy,generateKV,generateVideoStoryboard,generateCreatorBrief} from '@/services/content';import {assetPath} from '@/services/mock';import type {SocialPlatform,ContentFields} from '@/types/content';
const tabs=['社交平台文案','主视觉','视频分镜脚本','达人 Brief'];const context={projectId:'tmall-autumn-2026',brand:'天猫',objective:'天猫秋上新'};
function Fields({value}:{value:ContentFields}){return <dl className="grid gap-4 mt-6">{Object.entries(value).map(([key,text])=><div key={key} className="border-b border-black/15 pb-4"><dt className="eyebrow">{key}</dt><dd className="mt-2 whitespace-pre-line leading-7">{text}</dd></div>)}</dl>}
export function Studio(){const [tab,setTab]=useState(tabs[0]),[platform,setPlatform]=useState<SocialPlatform>('xiaohongshu'),[copy,setCopy]=useState(socialContent.xiaohongshu[0]),[variant,setVariant]=useState(0),[kv,setKv]=useState(kvStyles[0]),[video,setVideo]=useState(videoStoryboard),[direction,setDirection]=useState('穿搭'),[brief,setBrief]=useState(creatorBrief['穿搭']),[busy,setBusy]=useState(false),[status,setStatus]=useState('Mock 演示，可替换真实 API'),[playing,setPlaying]=useState(false),[frame,setFrame]=useState(0);
useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setFrame(n=>{if(n>=9){setPlaying(false);return 9}return n+1}),3000);return()=>clearInterval(timer)},[playing]);
async function run(task:()=>Promise<void>){setBusy(true);setStatus('AI生成中…');try{await task();setStatus('已生成 · Mock 演示')}catch{setStatus('操作失败，请重试。')}finally{setBusy(false)}}
function switchPlatform(p:SocialPlatform){setPlatform(p);setCopy(socialContent[p][0]);setVariant(0);setStatus('已切换平台 · '+(p==='xiaohongshu'?'小红书':'抖音'))}
async function copyText(){try{await navigator.clipboard.writeText(Object.entries(copy).map(([k,v])=>k+'：'+v).join('\n\n'));setStatus('已复制文案')}catch{setStatus('浏览器未允许复制，请选择正文手动复制。')}}
return <><div className="flex gap-2 overflow-x-auto border-b border-black/15" role="tablist">{tabs.map(t=><button role="tab" aria-selected={tab===t} disabled={busy} key={t} className={'studio-tab '+(tab===t?'selected':'')} onClick={()=>{setTab(t);setPlaying(false);setStatus('Mock 演示，可替换真实 API')}}>{t}</button>)}</div><p className="my-4 text-sm" role="status" aria-live="polite">{status}</p><div aria-busy={busy}>
{tab===tabs[0]&&<div className="grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="panel p-6"><p className="eyebrow">平台 / Platform</p><div className="flex gap-2 my-5">{(['xiaohongshu','douyin'] as const).map(p=><button key={p} aria-pressed={platform===p} disabled={busy} className={p===platform?'btn':'btn-light'} onClick={()=>switchPlatform(p)}>{p==='xiaohongshu'?'小红书':'抖音'}</button>)}</div><p>根据平台语境分别生成生活图文与短视频口播。</p><button className="btn mt-6" disabled={busy} onClick={()=>run(async()=>{const n=variant+1;setCopy(await generateCopy(platform,n,context));setVariant(n)})}>{busy?'AI生成中…':'Generate Copy / 重新生成'}</button></aside><article className="panel p-7"><div className="flex justify-between items-center"><span className={'platform-mark '+platform}>{platform==='xiaohongshu'?'小红书 RED':'♪ 抖音 Douyin'}</span><button className="btn-light" onClick={copyText}>复制文案</button></div><Fields value={copy}/></article></div>}
{tab===tabs[1]&&<><div className="flex flex-wrap gap-2 my-5">{kvStyles.map((s,i)=><button aria-pressed={kv.id===s.id} disabled={busy} className={kv.id===s.id?'btn':'btn-light'} key={s.id} onClick={()=>run(async()=>setKv(await generateKV(s.id,context)))}>{String(i+1).padStart(2,'0')} {s.label}</button>)}</div><div className="grid border border-black/15 lg:grid-cols-[1.3fr_1fr]"><div><img src={assetPath(kv.image)} alt={kv.label+' 本地主视觉示意图'} className="w-full h-full object-cover"/></div><div className="p-7"><p className="eyebrow">本地 SVG Demo / 非生成照片</p><Fields value={{'Creative Direction':kv.direction,'关键词':kv.keywords.join(' / '),'Art Direction':kv.artDirection,'Creative Rationale':kv.rationale,'应用建议':kv.application}}/><a className="btn-light mt-5" href={assetPath(kv.image)} download>下载当前主视觉 SVG</a></div></div></>}
{tab===tabs[2]&&<><button className="btn" disabled={busy} onClick={()=>run(async()=>{setVideo(await generateVideoStoryboard(context));setFrame(0);setPlaying(false)})}>{busy?'AI生成中…':'Generate Storyboard / 生成分镜'}</button><h2 className="mt-8">01 Video Concept</h2><p className="my-4">{video.concept}</p><h2>02 30s Script</h2><p className="my-4 whitespace-pre-line leading-7">{video.script}</p><h2 className="my-5">03 Shot List</h2><div className="overflow-x-auto"><table className="shot-table"><thead><tr>{['时间','画面','景别','人物动作','旁白/台词','屏幕字幕','声音','转场','产品露出','拍摄备注'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{video.shots.map(s=><tr key={s.time}>{[s.time,s.visual,s.size,s.action,s.voice,s.subtitle,s.sound,s.transition,s.product,s.notes].map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div><h2 className="my-6">04 Storyboard</h2><div className="grid gap-4 md:grid-cols-3 xl:grid-cols-5">{video.shots.map((s,i)=><button className="panel text-left p-3" key={s.time} onClick={()=>{setFrame(i);setPlaying(false)}}><img src={assetPath(s.frame)} alt={'镜头 '+(i+1)+' 占位示意'} className="w-full"/><p className="mt-3">{s.time} · {s.visual}</p></button>)}</div><h2 className="my-6">05 Demo Preview</h2><p className="mb-4">30秒分镜轮播演示，不含真实视频或音轨。</p><div className="panel p-5 max-w-3xl"><img src={assetPath(video.shots[frame].frame)} alt={video.shots[frame].visual} className="w-full"/><p className="my-3">{video.shots[frame].time} · {video.shots[frame].voice}</p><button className="btn-light" onClick={()=>{if(frame===9)setFrame(0);setPlaying(!playing)}}>{playing?'暂停预览':'播放分镜序列'}</button><button className="btn-light ml-2" onClick={()=>{setFrame(0);setPlaying(false)}}>重置</button></div></>}
{tab===tabs[3]&&<><h2>达人 Brief <span className="eyebrow">Creator Brief</span></h2><div className="grid gap-4 mt-6 md:grid-cols-3">{[['01 内容要点',creatorGuidelines.points],['02 品牌露出要求',creatorGuidelines.brand],['03 必带话题',creatorGuidelines.topics]].map(([title,items])=><section className="panel p-5" key={String(title)}><h3>{title}</h3><ul className="mt-4 space-y-3">{(items as string[]).map(item=><li key={item}>{item}</li>)}</ul></section>)}</div><h2 className="my-6">04 衍生方向</h2><div className="flex flex-wrap gap-2">{Object.keys(creatorBrief).map(d=><button className={direction===d?'btn':'btn-light'} aria-pressed={direction===d} disabled={busy} key={d} onClick={()=>run(async()=>{setBrief(await generateCreatorBrief(d,context));setDirection(d)})}>{d}</button>)}</div><Fields value={{'Content Angle':brief.angle,'内容场景':brief.scene,'推荐商品类型':brief.products,'开头Hook':brief.hook,'内容结构':brief.structure}}/></>}
</div></>}
