"use client";
import { useState } from "react";
import { ArrowUpRight, Copy, Download, Play, Sparkles } from "lucide-react";
const tabs=["Social","Copy","KV","Storyboard","Video","KOL Brief","PR","Presentation"];
const script=[
 ["0–03s","清晨，窗帘被风吹开，一只手摸到微凉的床单。","特写","秋天到底应该怎么过？","风声，布料摩擦"],
 ["03–08s","城市里不同的人打开各自的“秋天使用说明”。","快速组接","没有标准答案。","轻快鼓点进入"],
 ["08–15s","小个子女孩叠穿、户外男生装包、独居青年煮栗子。","中景 / 特写","有人把秋天穿在身上，有人走进山里。","生活环境声"],
 ["15–22s","手机路线与真实街区交叠，任务被逐一完成。","跟拍","你的习惯，就是秋天的坐标。","脚步与城市声"],
 ["22–27s","七张不同说明书在画面中铺开。","俯拍","一万个人，就有一万种秋天。","音乐推高"],
 ["27–30s","天猫红猫与主标题出现。","定帧","上天猫，找到你的秋天使用说明。","品牌声音标识"]
];
export function Studio(){const [active,setActive]=useState("Social");const [style,setStyle]=useState("Editorial");return <><div className="flex gap-1 overflow-x-auto border-b border-black/15">{tabs.map(x=><button onClick={()=>setActive(x)} key={x} className={`shrink-0 border-b-2 px-4 py-4 text-xs font-medium ${active===x?"border-black text-black":"border-transparent text-black/40"}`}>{x}</button>)}</div><div className="pt-8">{active==="Social"&&<div className="grid gap-6 lg:grid-cols-[320px_1fr]"><aside className="panel p-5"><p className="eyebrow">Generation controls</p>{[["Platform","小红书"],["Creator Type","生活方式"],["Tone","真实 / 年轻 / 非广告"]].map(([a,b])=><div key={a} className="border-b border-black/15 py-5"><p className="eyebrow">{a}</p><p className="mt-2 text-sm">{b}</p></div>)}<button className="btn mt-6 w-full"><Sparkles size={14}/> Regenerate</button></aside><article className="bg-white p-7 shadow-[0_20px_70px_rgba(0,0,0,.08)] md:p-10"><div className="flex items-center justify-between"><span className="rounded-full bg-[#ff2442] px-3 py-1 text-[10px] font-semibold text-white">小红书 DEMO</span><Copy size={16}/></div><h2 className="mt-10 font-serif text-3xl">没有标准答案的秋天，反而更好过了 🍂</h2><div className="mt-6 space-y-4 text-[15px] leading-7 text-black/70"><p>以前每到换季，我都像在赶一份秋天的进度表：要去看银杏、要买风衣、要喝第一杯热拿铁。</p><p>今年试了天猫的「一万种秋天使用说明」，结果我的秋日人格居然叫——<strong>低能量漫游者</strong>。</p><p>它没让我去热门景点排队，只给了三个很小的任务：下班提前一站走回家；找一件摸起来安心的针织衫；周六去旧街区买刚出炉的栗子。</p><p>原来秋天不是一张待完成的清单。适合我的速度、温度和路线，就是我的秋天。</p><p>你会是哪一种？在天猫搜「秋天使用说明」，领走你的周末路线。</p></div><p className="mt-7 text-sm text-[#3159b7]">#一万种秋天使用说明 #天猫秋季焕新 #适合比流行重要 #周末去哪儿</p></article></div>}
{active==="KV"&&<div><div className="mb-6 flex flex-wrap gap-2">{["Editorial","Documentary","Fashion","Minimal","Surreal","Youth Culture"].map(x=><button key={x} onClick={()=>setStyle(x)} className={`rounded-full border px-4 py-2 text-xs ${style===x?"border-black bg-black text-white":"border-black/15"}`}>{x}</button>)}</div><div className="grid overflow-hidden border border-black/20 lg:grid-cols-[1.25fr_.75fr]"><div className="relative min-h-[610px] overflow-hidden bg-[#d4b29b] p-8 md:p-12"><div className="absolute -right-20 -top-24 h-96 w-96 rounded-full bg-[#ff6238] blur-3xl opacity-65"/><div className="absolute bottom-[-80px] left-[20%] h-80 w-80 rounded-full bg-[#8f2d18] blur-3xl opacity-55"/><div className="absolute inset-x-[34%] bottom-0 top-0 rotate-[16deg] bg-[#e8dfc9]/70 shadow-2xl"/><p className="relative z-10 text-[10px] font-semibold uppercase tracking-[.2em]">TMALL AUTUMN / 2026</p><h2 className="relative z-10 mt-16 max-w-xl font-serif text-6xl leading-[.95] tracking-[-.06em] md:text-8xl">一万种<br/><span className="italic">秋天</span><br/>使用说明</h2><div className="absolute bottom-10 left-8 right-8 z-10 flex items-end justify-between md:left-12 md:right-12"><p className="max-w-[250px] text-xs leading-relaxed">没有标准答案。<br/>找到适合你的温度、路线与生活。</p><span className="grid h-24 w-24 place-items-center rounded-full bg-acid text-center text-xs font-bold">SCAN YOUR<br/>AUTUMN</span></div></div><div className="bg-ink p-7 text-white"><p className="eyebrow !text-white/40">Creative direction</p><p className="mt-3 font-serif text-3xl">Product Manual × Autumn Lifestyle Photography</p><div className="mt-14 space-y-5 border-t border-white/15 pt-6 text-sm text-white/60"><p><span className="eyebrow !text-white/30">Visual mode</span><br/>{style}</p><p><span className="eyebrow !text-white/30">Palette</span><br/>Burnt persimmon / Oat / Acid lime</p><p><span className="eyebrow !text-white/30">Typography</span><br/>Editorial serif × Utility grotesk</p></div><button className="mt-12 inline-flex items-center gap-2 border-b border-white pb-1 text-xs"><Download size={13}/> Export key visual</button></div></div></div>}
{active==="Storyboard"&&<div className="overflow-x-auto"><table className="w-full min-w-[900px] border-collapse text-left"><thead><tr className="border-y border-black/20 text-[9px] uppercase tracking-[.15em] text-black/45">{["秒数","画面","景别","文案","声音"].map(x=><th key={x} className="px-4 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{script.map((r,i)=><tr key={i} className="border-b border-black/15 align-top hover:bg-white/50">{r.map((c,j)=><td key={j} className={`px-4 py-5 text-sm leading-relaxed ${j===0?"font-mono text-xs":j===1?"max-w-sm font-medium":"text-black/60"}`}>{c}</td>)}</tr>)}</tbody></table><button className="btn mt-7"><Play size={14}/> Preview sequence</button></div>}
{!["Social","KV","Storyboard"].includes(active)&&<div className="grid min-h-[460px] place-items-center border border-black/15 bg-white/40 text-center"><div><p className="eyebrow">{active} generator</p><h2 className="mt-5 font-serif text-4xl">Ready for the next iteration.</h2><p className="mx-auto mt-4 max-w-md text-sm leading-relaxed text-black/50">此模块已预留Agent与生成式API接入位。当前MVP聚焦Social、KV与Storyboard三项核心资产。</p><button className="btn-light mt-7">Open module <ArrowUpRight size={13}/></button></div></div>}</div></>}
